name: 'Check for AB#'
description: 'Check if the pull request is linked to a work item in Azure DevOps'
author: 'danhellem'
branding:
  icon: "code"
  color: " purple"
inputs:
  repo-token:
    description: 'Github token of the repository (automatically created by GitHub)'
    default: ${{ github.token }}
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
